Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
all_var_names = ['Temperature Anomaly', 'Carbon Concentration Dynamics', 'Carbon Emission', 'Impulse Response Function']
selected_index = [all_var_names.index(element) for element in simulate_external.value]
# print(selected_index)

# for j in selected_index:
#     print(j+1)

fig, ax = plot_simulation(pulsesize, pulseyear,pulsebaseline,pulsecearth, selected_index)
plt.tight_layout()
plt.show()
# Image("test2.png")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32mC:\Users\ALIENW~1\AppData\Local\Temp/ipykernel_27276/2071115236.py[0m in [0;36m<module>[1;34m[0m
[0;32m      6[0m [1;31m#     print(j+1)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m [1;33m[0m[0m
[1;32m----> 8[1;33m [0mfig[0m[1;33m,[0m [0max[0m [1;33m=[0m [0mplot_simulation[0m[1;33m([0m[0mpulsesize[0m[1;33m,[0m [0mpulseyear[0m[1;33m,[0m[0mpulsebaseline[0m[1;33m,[0m[0mpulsecearth[0m[1;33m,[0m [0mselected_index[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      9[0m [0mplt[0m[1;33m.[0m[0mtight_layout[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     10[0m [0mplt[0m[1;33m.[0m[0mshow[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\QuantClimateChange\Module_plot.py[0m in [0;36mplot_simulation[1;34m(pulse, year, baseline, cearth, selected_index)[0m
[0;32m     28[0m     [1;32mfor[0m [0mj[0m [1;32min[0m [0mselected_index[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     29[0m [1;33m[0m[0m
[1;32m---> 30[1;33m         [0maxs[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mmodelsol[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m,[0m [0mmodelsol[0m[1;33m[[0m[0mj[0m[1;33m+[0m[1;36m1[0m[1;33m][0m[1;33m,[0m[0mcolor[0m[1;33m=[0m[0mcolors[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m,[0m [0mlabel[0m[1;33m=[0m[1;34mf"cearth={cearth},pulse={pulse}"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     31[0m         [0maxs[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m.[0m[0mset_ylabel[0m[1;33m([0m[0mylabels[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     32[0m         [0maxs[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m.[0m[0mset_title[0m[1;33m([0m[0mtitles[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: 'AxesSubplot' object is not subscriptable
TypeError: 'AxesSubplot' object is not subscriptable

